// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IncidentesAPI.Models
{
    public partial class Aplicacion
    {
        public Aplicacion()
        {
            Incidentes = new HashSet<Incidente>();
        }

        public int AplicacionesId { get; set; }
        public string TipoAplicativo { get; set; }
        public string Descripcion { get; set; }
        public int AreasId { get; set; }

        public virtual Area Areas { get; set; }
        public virtual ICollection<Incidente> Incidentes { get; set; }
    }
}