// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IncidentesAPI.Models
{
    public partial class Incidente
    {
        public int IncidenteId { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public int Prioridad { get; set; }
        public DateTime Fecha { get; set; }
        public int UsuariosId { get; set; }
        public int AplicacionesId { get; set; }

        public virtual Aplicacion Aplicaciones { get; set; }
        public virtual Usuario Usuarios { get; set; }
    }
}