// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IncidentesAPI.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            Incidentes = new HashSet<Incidente>();
        }

        public int UsuariosId { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public int RolesId { get; set; }

        public virtual Rol Roles { get; set; }
        public virtual ICollection<Incidente> Incidentes { get; set; }
    }
}